### PR TITLE
Update to proto3

### PR DESCRIPTION
**Pull request by tamird**
First commit is the source dump, second commit is more interesting

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM

**Comment by bdarnell** [comment]
LGTM. I had proposed this in #1 and we had decided to wait until a final release was available. Is there any particular reason to make the switch now while it's still alpha?

**Comment by tamird** [comment]
It doesn't really hurt anything - it's all backwards compatible until we start using `syntax=proto3`. gogoproto has merged the proto3 branch, so this felt like a good-to-do.

**Comment by bdarnell** [comment]
Cool. I'll also work on automating the clean proto generation with `proto-rewrite` then.

**Pull request merged**
