### PR TITLE
Terminate c-jemalloc import string.

### PR DESCRIPTION
**Pull request by petermattis**

### CODE REVIEW

**Comment by petermattis** [comment]
How was this working?

**Comment by tamird** [comment]
Dag, I broke this yesterday. LGTM

**Comment by petermattis** [comment]
@tamird Do you mind bumping the dependency in the `cockroach/GLOCKFILE`? I'm about to head into an interview.

**Comment by mberhault** [comment]
I last pushed to the jemalloc branch yesterday. Its `GLOCKFILE` has `c-protobuf` before the break (sha 6362977a9a1989062dccfa5fe314d6c864e7590c), so nothing surprising there. Weird change though.

**Pull request merged**
