### PR TITLE
(wip) update 3.0.0-beta-1

### PR DESCRIPTION
**Pull request by tbg**
I couldn't quite get it to work. During `./import.sh`, there are warnings

```
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... -D_THREAD_SAFE
checking whether to check for GCC pthread/shared inconsistencies... no
checking whether what we have so far is sufficient with -nostdlib... no
checking whether -lpthread saves the day... no
configure: WARNING: Impossible to determine how to use pthreads with shared libraries and -nostdlib
```

and they come true:

``` bash
$ go build .
# github.com/cockroachdb/c-protobuf
./common.cc:51:2: error: "No suitable threading library available."
```

I'm not sure whether I removed something that made this work (due to numerous file changes, I didn't want to stick with the old import script and "keep" most of the files - I wiped everything and updated the scripts so that they would work then) or whether the `pthread` issue is just "new".
This also brings up bad memories of linking `pthread` statically.

### CODE REVIEW

**Comment by bdarnell** [comment]
google/protobuf#74 suggests that this may be a problem with the version of libtool you're using.

We shouldn't be running `autogen.sh` if we can avoid it: this uses your local autoconf/automake versions which can have unpredictable results. If we download the [protobuf-cpp release tarball](https://github.com/google/protobuf/releases/download/v3.0.0-beta-1/protobuf-cpp-3.0.0-beta-1.tar.gz) instead of the tarball that is autogenerated from the git repo, the configure script is already present so we don't need to run `autogen.sh`. Does that work for you?

**Comment by tbg** [comment]
Nope, same behaviour (but I've updated `./import.sh` with your suggestions).

**Comment by bdarnell** [comment]
It's not just you; I get the same failure on my machine.

**Comment by petermattis** [comment]
Your `import.sh` mostly worked for me. Related to OS X version? I'm on El Capitan (10.11.1). 

We'll need to add `-DHAVE_PTHREAD` to `cgo_flags.go`. And the list of `PROTOC` sources wasn't quite correct for me. It was stripping out stuff like `bytestream.cc` do to look naively for `test` in the path name.

**Comment by tbg** [comment]
touched up by @petermattis in #7.

**Pull request closed without merging**
